version = 0.1
[default.deploy.parameters]
stack_name = "kand2035stack"
s3_bucket = "kand2035sam"
s3_prefix = "kand2035prefix"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
